Nullability
Kotlin/ggdsl pull request #94
Opened 2023-01-20 22:58 UTC by AndreiKingsley

2023-01-23 09:47 UTC, devcrocod commented on settings.gradle.kts
> +//include("ggdsl-echarts")
try not to disable modules

2023-01-23 11:10 UTC, devcrocod commented on ggdsl-api/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/dsl/column/columnPointer.kt
> +public inline operator fun <reified T> String.invoke(): ColumnPointer<T> =
Shouldn't it be `Any?`?

2023-01-25 16:49 UTC, devcrocod requested changes

2023-01-25 16:49 UTC, devcrocod commented on ggdsl-api/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/dsl/scale.kt
> +    nullValue: RangeType? = null,
why is `nullValue` not `DomainType`?

2023-01-25 16:49 UTC, devcrocod commented on ggdsl-api/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/dsl/scale.kt
> +    nullValue: RangeType? = null,
why is `nullValue` not `DomainType`?

2023-01-25 16:49 UTC, devcrocod commented on ggdsl-api/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/dsl/scale.kt
> +    nullValue: RangeType? = null,
why is `nullValue` not `DomainType`?

2023-01-25 16:56 UTC, devcrocod commented on ggdsl-api/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/dsl/scale.kt
> +    categories: List<DomainType & Any>? = null,
why is there an intersection of `DomainType` and `Any`? I can't specify null in categories.
Why do we need an intersection at all?

2023-02-07 12:17 UTC, AndreiKingsley commented
#90
#91

2023-02-08 12:27 UTC, devcrocod approved these changes

2023-02-08 13:38 UTC, merged