new jupyter render
Kotlin/ggdsl pull request #98
Opened 2023-01-30 11:28 UTC by AndreiKingsley

2023-02-01 11:59 UTC, AndreiKingsley commented
#92

2023-02-06 10:46 UTC, ileasile commented on ggdsl-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/letsplot/Integration.kt
> +            else -> TODO()
Looks unsafe)) Won't it be a case for `PlotGrid`?

2023-02-06 10:46 UTC, ileasile commented on ggdsl-util/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/util/serialization/specSerialization.kt
> +internal typealias Spec = Map<String, Any>
Maybe make it public/rename to `LetsPlotSpec`?

2023-02-06 10:49 UTC, AndreiKingsley commented on ggdsl-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/letsplot/Integration.kt
> +            else -> TODO()
Taken from lets-plot; PlotGrid is actually GGBunch.

2023-02-06 10:50 UTC, AndreiKingsley commented on ggdsl-util/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/util/serialization/specSerialization.kt
> +internal typealias Spec = Map<String, Any>
ok

2023-02-06 11:40 UTC, devcrocod requested changes

2023-02-06 11:40 UTC, devcrocod commented on ggdsl-echarts/src/test/kotlin/org/jetbrains/kotlinx/ggdsl/echarts/jupyter/MonoIntegrationTest.kt
> +        assertEquals(resource.readText().replace("\r\n", "\n"), actualOutputText)
why is it needed?

2023-02-06 11:40 UTC, devcrocod commented on ggdsl-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/letsplot/Integration.kt
> +            else -> TODO()
Add exception in `else` case

2023-02-06 11:40 UTC, devcrocod commented on ggdsl-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/letsplot/Integration.kt
> +        val spec = toSpec()
do we always convert both spec and html? Can we know in advance which render will be needed?

2023-02-06 11:40 UTC, devcrocod commented on gradle.properties
> +version = 0.3.1
if you publish, then do it only dev version for now

2023-02-06 11:40 UTC, devcrocod commented on settings.gradle.kts
> +include("ggdsl-util")
why do you need a new module? Will it be published or will it be embedded?

2023-02-06 11:40 UTC, devcrocod commented on ggdsl-util/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/util/serialization/specSerialization.kt
> +        json.booleanOrNull ?:
maybe it's better to use `when`?

2023-02-06 11:47 UTC, AndreiKingsley commented on ggdsl-echarts/src/test/kotlin/org/jetbrains/kotlinx/ggdsl/echarts/jupyter/MonoIntegrationTest.kt
> +        assertEquals(resource.readText().replace("\r\n", "\n"), actualOutputText)
to support breaks formatting of git on Windows.

2023-02-06 11:48 UTC, AndreiKingsley commented on ggdsl-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/letsplot/Integration.kt
> +        val spec = toSpec()
@ileasile

2023-02-06 11:48 UTC, ileasile commented on ggdsl-echarts/src/test/kotlin/org/jetbrains/kotlinx/ggdsl/echarts/jupyter/MonoIntegrationTest.kt
> +        assertEquals(resource.readText().replace("\r\n", "\n"), actualOutputText)
If testdata was checked out as CRLF, we "fix" it here

2023-02-06 11:50 UTC, AndreiKingsley commented on settings.gradle.kts
> +include("ggdsl-util")
@ileasile

2023-02-06 11:51 UTC, ileasile commented on ggdsl-util/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/util/serialization/specSerialization.kt
> +        json.booleanOrNull ?:
I don't know how to use when since JsonPrimitive is the final type. The only thing it can say it's if the literal is wrapped with quotes (it's isString check)

2023-02-06 11:52 UTC, ileasile commented on settings.gradle.kts
> +include("ggdsl-util")
It should be published, I want to reuse the deserialization code on plugin side and don't want to copy-paste

2023-02-06 11:54 UTC, ileasile commented on ggdsl-util/build.gradle.kts
> +    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:$serialization_version")
It should be an API dependency

2023-02-06 11:56 UTC, AndreiKingsley commented on ggdsl-util/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/util/serialization/specSerialization.kt
> +        json.booleanOrNull ?:
ok

2023-02-06 12:24 UTC, ileasile commented on ggdsl-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/letsplot/Integration.kt
> +        val spec = toSpec()
We need html for browser and spec for Kotlin Notebooks. Common way is to provide both in such cases, but you can use `notebook.jupyterClientType` to select what you will send. WARNING! In this case notebooks that were executed in browser, will be opened in Kotlin Notebook with non-fancy JCEF outputs, and notebooks that were executed in Kotlin Notebook will be opened in browser with MISSING outputs

2023-02-06 13:36 UTC, ileasile approved these changes

2023-02-06 13:52 UTC, devcrocod commented on ggdsl-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/letsplot/Integration.kt
> +        val spec = toSpec()
ok, let's leave it
Although it seemed to me that it would still be necessary to re-execute the notebook cells from the browser in the idea and vice versa, for normal output

2023-02-06 13:55 UTC, devcrocod approved these changes

2023-02-06 14:28 UTC, ileasile commented on ggdsl-lets-plot/src/main/kotlin/org/jetbrains/kotlinx/ggdsl/letsplot/Integration.kt
> +        val spec = toSpec()
It shouldnät be needed

2023-02-07 09:26 UTC, merged